- name: docker compose down
  hosts: localhost
  vars_files: vars/test.yaml
  tasks:
    - name: docker compose down
      shell: docker rm -f "{{project_name}}_nginx_1" && docker rm  -f "{{project_name}}_php_1"
