services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./sites/:/app
    networks:
      - productionNet
    restart: always
    depends_on:
      - php

  php:
    image: php:7-fpm
    networks:
      - productionNet
    restart: always
    volumes:
      - ./sites/:/app


networks:
  productionNet: